package rules

import com.my.model.Address;
import com.my.model.AddressCheckResult;

global java.util.List myGlobalList;

function String hello1(String name) {

 return "Hello1 " + name + "!";
}


rule "myrules.drl-1"
lock-on-active
 timer (1s 2s)
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
         myGlobalList.add( "myrules.drl-1");
        System.out.println("规则中打印日志：校验通过!");
        System.out.println(hello("myrules.drl-1"));

       // 如果满足某个条件，使用 halt 终止计时器
        if (/* 某些条件 */ true) {
            System.out.println("Terminating timer.");
            drools.halt(); // 终止计时器并抛出异常
        }
end

rule "2017myrules.drl-2"
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
         myGlobalList.add( "2017myrules.drl-2" );
        System.out.println("规则中打印日志：校验通过2017!");
end